<?php

module_load_include('inc', 'bookbox', 'bookbox.functions');
module_load_include('inc', 'bookbox', 'bookbox.forms');
module_load_include('inc', 'bookbox', 'bookbox.cart');
module_load_include('inc', 'bookbox', 'bookbox.readnow');
module_load_include('inc', 'bookbox', 'bookbox.adminmessages');

function bookbox_menu(){
  $items=array();
  
  $items['admin/bookbox/labels'] = array(
      'title' => 'Bookbox admin labels',
      'description' => 'Admin labels',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('bookbox_admin_labels_form'),
      'access arguments' => array('access adminstration page'),
      'access callback' => TRUE,
  );
  
  return $items;
}

function bookbox_block_info() {
  $blocks = array();

  $blocks['MiniCart'] = array(
    'info' => t('Mini cart'),
  );

  $blocks['ReadingNow'] = array(
      'info' => t('Reading now'),
  );

  return $blocks;
}

function bookbox_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'MiniCart':
      $block['subject'] = '';
      $form = drupal_get_form('bookbox_mini_cart_block');
      $block['content'] = drupal_render($form);
      break;

    case 'ReadingNow':
      $block['subject'] = '';
      $form = drupal_get_form('bookbox_reading_now_block');
      $block['content'] = drupal_render($form);
      break;
  }

  return $block;
}

function bookbox_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state) {
  // можно добавить максимум 2
  // а если есть книжка из заказа прошлого месяца то 1
  // а если 2 то 0
  $can_add2cart = true;
  $in_prolong = 0;
  $in_cart = 0;


  if (isset($form['product_id'])) {
    $form_product = $form['product_id']['#value'];
  }

  $wrapper = _bookbox_get_cart_items();

  //что-то есть в корзине
  if ($wrapper) {
    foreach ($wrapper->commerce_line_items as $delta => $line_item_wrapper) {
      $cart_product = $line_item_wrapper->commerce_product->value()->product_id;
      $in_cart = $in_cart + 1;

      if($form_product == $cart_product) {
        $can_add2cart = false; // если эта книга уже в корзине, то нечего ее добавлять, ок, да?
        break;
      }
    }
  }

  $prolong = bookbox_get_in_prolong();

  //что-то продлено
  if($prolong) {
    foreach($prolong as $item) {
      if ($item->status == 'prolong') {
        $in_prolong = $in_prolong + 1;
      }
    }
  }

  if ($in_cart + $in_prolong >= 2) {
    $can_add2cart = false;
  }

  if (!$can_add2cart) {
    $form['submit']['#attributes']['disabled'] = TRUE;
  }
}
